name: build-cache-nix

on:
  push:

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v35
      - run: nix build --print-build-logs
