name: build-magic-nix-cache

on:
  push:

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - run: nix build --print-build-logs
