name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - flake.lock
      - .github/workflows/seed.yaml
  workflow_run:
    workflows:
      - seed
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: roundtablelove/nix-seed@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_name: <name>
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
